<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>simple.orm</groupId>
    <artifactId>simple-orm-parent</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>

    <modules>
        <module>jdbc-wrap</module>
        <module>util</module>
        <!--<module>xxx</module>-->
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- self version -->
        <revision>0.1</revision>
        <!-- library versions -->
        <vavr.version>0.11.0</vavr.version>
        <!--<slf4j.version>2.0.17</slf4j.version>-->
        <log4j.version>2.25.3</log4j.version>
        <junit.version>6.0.2</junit.version>
        <mockito.version>5.21.0</mockito.version>
        <assertj.version>3.27.7</assertj.version>
        <h2.version>2.4.240</h2.version>
        <maven.surefire.version>3.5.4</maven.surefire.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-bom</artifactId>
                <version>${mockito.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.vavr</groupId>
            <artifactId>vavr</artifactId>
            <version>${vavr.version}</version>
        </dependency>

        <!-- logging for tests only for now -->
        <!--<dependency>-->
        <!--    <groupId>org.slf4j</groupId>-->
        <!--    <artifactId>slf4j-api</artifactId>-->
        <!--    <version>${slf4j.version}</version>-->
        <!--</dependency>-->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>${log4j.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- for tests -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${h2.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <configuration>
                    <!--<systemPropertyVariables>-->
                    <!--    <java.io.tmpdir>${project.build.directory}/surefire-tmp</java.io.tmpdir>-->
                    <!--</systemPropertyVariables>-->
                    <testClassesDirectory>${project.build.directory}/test-classes</testClassesDirectory>
                    <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
                    <classesDirectory>${project.build.directory}/classes</classesDirectory>
                    <tempDir>surefire-tmp</tempDir>
                    <!--<useFile>false</useFile>-->
                    <!--<testFailureIgnore>true</testFailureIgnore>-->
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
